### ISSUE TITLE
EPERM error when cleaning on windows

### ISSUE THREAD

**Issue by LunarDevelopment** [mwaylabs/generator-m-ionic#223]
Ola! 

I'm getting the below error whenever I alter a SASS file, I've tried with multiple new projects. 
node: v0.12.4
npm: 2.10.1
generator-m: latest `npm install` version 

Any assistance would be greatly appreciated! 

```sh
Started connect web server on http://localhost:9000
[13:47:55] gulp-inject 1 files into main\constants\config-const.js.
[13:47:55] Finished 'clean' after 2.64 s
[13:47:55] Starting 'styles'...
[13:47:56] Finished 'jsonlint' after 1.98 s
[13:47:56] Finished 'wiredep' after 4.09 s
[13:47:56] Finished 'environment' after 3.82 s
[13:47:56] Starting 'build-vars'...
[13:48:02] gulp-inject 1 files into main\constants\config-const.js.
[13:48:02] Finished 'styles' after 6.79 s
[13:48:02] Finished 'jscs' after 8.12 s
[13:48:02] Finished 'jshint' after 8.93 s
[13:48:02] Starting 'linting'...
[13:48:02] Finished 'linting' after 24 µs
[13:48:02] Finished 'build-vars' after 5.35 s
[13:48:02] Finished 'bower-fonts' after 9.45 s
[13:48:02] Starting 'inject-all'...
[13:48:02] gulp-inject 6 files into index.html.
[13:48:02] gulp-inject 1 files into index.html.
[13:48:02] Finished 'inject-all' after 554 ms
[13:48:02] Starting 'serve'...
[13:48:02] Finished 'serve' after 21 ms
[13:48:02] Starting 'watch'...
[13:48:03] Finished 'watch' after 1.13 s
[13:48:10] Starting 'clean'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch EPERM
    at exports._errnoException (util.js:746:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1157:26)

C:\wamp\www\Projects\ionic\themes\edgy>gulp watch
```

**Comment by gruppjo** [comment]
Hi @LunarDevelopment, are you working on windows?

These kind of problems are common on windows. They're related to the packages https://github.com/sindresorhus/del or https://github.com/gulpjs/gulp (I'm not sure). 

More info here:
https://github.com/mwaylabs/generator-m/issues/156

Please report back with any findings.

**Comment by jmartsch** [comment]
Hi. I got exactly the same problem. @LunarDevelopment is using windows, which I can see from his path: C:\wamp\www\
WAMP is a Windows/Apache/MySQL/PHP environment. 
I am using XAMPP, a similar project on Windows 10 with Node 0.12.4.

**Comment by jonathandemazy** [comment]
I have exactly the same error when my main.scss is open...

**Comment by jmartsch** [comment]
@jonathandemazy a quick "fix" would be to comment line 27 of gulp/building.js which reads
```
.pipe(vinylPaths(del));
```
I think the error is coming from del which works not correct on windows.

**Comment by jonathandemazy** [comment]
Yes it work.
But now gulp compile my scss file infinitly when it is open.

gulp.watch('app/*/styles/**/*.scss', ['styles']);

**Comment by jmartsch** [comment]
This is weird. Even when you are not typing or saving this file?
Maybe your editor does an autosave while typing?
If so, gulp would recompile everytime.

**Comment by jonathandemazy** [comment]
No i did nothing.
My file is just open by my editor.
If i close my file, it's ok, but when i open it, gulp recompile and recompile and recompile :)

For html js files... i don't have any problem.

**Comment by jmartsch** [comment]
Sorry, I can´t help you with this. I think your Editor does an autosave or has an internal file-watcher which triggers the endless recompiles.
Did you change your watch command in watching.js?
It has to be
```
 gulp.watch('app/*/styles/**/*.scss', ['styles']);
```

**Comment by geding** [comment]
I found solution, thanks to @havenchyk https://github.com/gulpjs/gulp/issues/738#issuecomment-60301017

We need to change it to be like this:
`return gulp.src(['.tmp/**/*.*', paths.dist + '/*'])`

**Comment by gruppjo** [comment]
Do you mean in `buildings.js`
```js
gulp.task('clean', function () {
  return gulp.src(['.tmp', paths.dist + '/*'])
    .pipe(vinylPaths(del));
});
```
this part?

**Comment by geding** [comment]
Hi @gruppjo, yes exactly this part

**Comment by gruppjo** [comment]
I'll implement this. Can anyone else confirm?

**Comment by gruppjo** [comment]
Closing this for now. Please comment if problem persists.
