### ISSUE TITLE
precommit hook husky guide

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#231]
package.json
```
"scripts": {
    "precommit": "gulp linting-throw"
 }
```

`npm install husky --save-dev`
https://github.com/typicode/husky

see #23 for further details

**Comment by MathiasTim** [comment]
I just tried adding a precommit hook with husky for the newest version of the [demo repo](https://github.com/mwaylabs/generator-m-demo).

I thought besides linting I'll add tests as well.

```
  "scripts": {
    "precommit": "gulp linting-throw && gulp karma && gulp protractor"
  },
```

But somehow if there is an error with tests (```gulp karma```) an error occurs and the task stops. Also occurs when just running ```gulp karma```. Log below.

Also the fact, that linting will run multiple times is not nice, but necessary I guess. Because we have to run ```gulp linting-throw```

```
$ git commit -am 'asd'
[13:09:36] Using gulpfile ~/Projects/test/generator-m-demo/gulpfile.js
[13:09:36] Starting 'eslint'...
[13:09:37] Starting 'jsonlint-throw'...
[13:09:38] Finished 'jsonlint-throw' after 522 ms
[13:09:38] 
/Users/mathiasmaier/Projects/test/generator-m-demo/app/main/controllers/blubb-ctrl.js
  5:8  error  Unexpected space between function name and paren  no-spaced-func

✖ 1 problem (1 error, 0 warnings)

[13:09:38] Finished 'eslint' after 1.58 s
[13:09:38] Starting 'linting-throw'...
[13:09:38] Finished 'linting-throw' after 13 μs
[13:09:40] Using gulpfile ~/Projects/test/generator-m-demo/gulpfile.js
[13:09:40] Starting 'eslint'...
[13:09:40] Starting 'jsonlint'...
[13:09:41] Finished 'jsonlint' after 441 ms
[13:09:41] 
/Users/mathiasmaier/Projects/test/generator-m-demo/app/main/controllers/blubb-ctrl.js
  5:8  error  Unexpected space between function name and paren  no-spaced-func

✖ 1 problem (1 error, 0 warnings)

[13:09:41] Finished 'eslint' after 1.3 s
[13:09:41] Starting 'linting'...
[13:09:41] Finished 'linting' after 12 μs
[13:09:41] Starting 'karma'...
05 09 2015 13:09:42.148:INFO [karma]: Karma v0.13.9 server started at http://localhost:9876/
05 09 2015 13:09:42.157:INFO [launcher]: Starting browser PhantomJS
05 09 2015 13:09:43.198:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket 5v3KbzW6Unelcv2WAAAA with id 85210177
PhantomJS 1.9.8 (Mac OS X 0.0.0) module: main, controller: DebugCtrl .grade() should classify asdfasdfasdf as strong FAILED
	Expected 'strongs' to equal 'strong'.
	    at /Users/mathiasmaier/Projects/test/generator-m-demo/test/karma/main/debug-ctrl.spec.js:33
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 10 of 10 (1 FAILED) (0.006 secs / 0.08 secs)
[13:09:43] 'karma' errored after 1.67 s
[13:09:43] Error: 1
    at formatError (/Users/mathiasmaier/Projects/test/generator-m-demo/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/mathiasmaier/Projects/test/generator-m-demo/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/mathiasmaier/Projects/test/generator-m-demo/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/mathiasmaier/Projects/test/generator-m-demo/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mathiasmaier/Projects/test/generator-m-demo/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/mathiasmaier/Projects/test/generator-m-demo/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/mathiasmaier/Projects/test/generator-m-demo/node_modules/karma/lib/server.js:325:7)
    at Server.<anonymous> (/Users/mathiasmaier/Projects/test/generator-m-demo/node_modules/karma/lib/server.js:336:9)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:129:20)
    at net.js:1409:10
    at process._tickCallback (node.js:355:11)

husky - pre-commit hook failed (add --no-verify to bypass)

```

**Comment by gruppjo** [comment]
https://m-wayteam.slack.com/files/m.maier/F1ECWJGSG/pre_commit_hooks__husky_.md
