### ISSUE TITLE
Problem running gulp watch

### ISSUE THREAD

**Issue by willmkt** [mwaylabs/generator-m-ionic#276]
Hi, when i run gulp watch i get the following erros:

```
/Users/will/Documents/Lab/generator-m-ionic-demo-master/node_modules/gulp-natural-sort/index.js:16
      return String.naturalCompare(a.relative.toLowerCase(), b.relative.toLowe
                    ^
TypeError: undefined is not a function
    at /Users/will/Documents/Lab/generator-m-ionic-demo-master/node_modules/gulp-natural-sort/index.js:16:21
    at Array.sort (native)
    at Stream.onEnd (/Users/will/Documents/Lab/generator-m-ionic-demo-master/node_modules/gulp-natural-sort/index.js:15:11)
    at _end (/Users/will/Documents/Lab/generator-m-ionic-demo-master/node_modules/gulp-natural-sort/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/will/Documents/Lab/generator-m-ionic-demo-master/node_modules/gulp-natural-sort/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/will/Documents/Lab/generator-m-ionic-demo-master/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at /Users/will/Documents/Lab/generator-m-ionic-demo-master/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
```
Even when i run then demo app.

Can someone help?

Thanks...

**Comment by gruppjo** [comment]
Hi @willmkt, I took the liberty of formatting your code.
This seems to be a problem with gulp-natural-sort. They recently release a new version. They release another one just 15 hours ago. Maybe you can try to run everything again?

**Comment by willmkt** [comment]
Hi @gruppjo, thanks for the code formatting.

I just update my app and it works now

Thanks for the help....
