### ISSUE TITLE
gulp protractor - tests not working

### ISSUE THREAD

**Issue by bagolol** [mwaylabs/generator-m-ionic#280]
Hello, 

this is my first ever issue on github, so please bear with me if I make mistakes in submitting it :)

I scaffolded my project using `yo m-ionic` and chose tabs and SASS and all cordova plugins as options. 

When I run `gulp protractor` right after the scaffolding has terminated the error message I get is the following:

```
1) Debug page should grade passwords
   Message:
     ElementNotVisibleError: element not visible
  (Session info: chrome=46.0.2490.86)
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.11.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 45 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'Roccos-Air.default', ip: '192.168.1.107', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/_m/rxjymxms1zz6_mzr_jhwjj880000gn/T/.org.chromium.Chromium.uzpd1G}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.86, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: f7e90aadf3578c0231561ed836fa1eb0
   Stacktrace:
     ElementNotVisibleError: element not visible
  (Session info: chrome=46.0.2490.86)
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.11.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 45 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'Roccos-Air.default', ip: '192.168.1.107', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/_m/rxjymxms1zz6_mzr_jhwjj880000gn/T/.org.chromium.Chromium.uzpd1G}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.86, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: f7e90aadf3578c0231561ed836fa1eb0
    at Array.forEach (native)
    at process._tickCallback (node.js:377:9)
Error
    at [object Object].<anonymous> (/Users/rocco/development/test/generator/test/protractor/main-debug.spec.js:15:19)
From: Task: Asynchronous test function: it()
Error
    at [object Object].<anonymous> (/Users/rocco/development/test/generator/test/protractor/main-debug.spec.js:9:3)
    at Object.<anonymous> (/Users/rocco/development/test/generator/test/protractor/main-debug.spec.js:3:1)

Finished in 1.13 seconds
1 test, 1 assertion, 1 failure

Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

I did a bit of research and someone suggested to tweak the protractor.conf.js file by adding this:
`onPrepare: function() {
    browser.driver.manage().window().maximize();
  },`

This changed the error message which is now the following: 
```
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.1.107:59929/wd/hub
F

Failures:

  1) Debug page should grade passwords
   Message:
     Expected '' to equal 'weak'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/rocco/development/test/generator/test/protractor/main-debug.spec.js:16:40)

  2) Debug page should grade passwords
   Message:
     Expected '' to equal 'medium'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/rocco/development/test/generator/test/protractor/main-debug.spec.js:21:40)

  3) Debug page should grade passwords
   Message:
     Expected '' to equal 'strong'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/rocco/development/test/generator/test/protractor/main-debug.spec.js:26:40)

Finished in 2.128 seconds
1 test, 6 assertions, 3 failures

Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 3 test(s)
[launcher] overall: 3 failed spec(s)
[launcher] Process exited with error code 1

/Users/rocco/development/test/generator/gulp/testing.js:42
      throw err;
      ^
Error: protractor exited with code 1
```

when looking at the test execution, it looks like protractor is actually performing "sendKeys", but the tests fail. I've been struggling with this issue for quite a while and did a lot of research on SO or similar, but I couldn't fix it. 

Please let me know if it a bug on my side or if it's a common issue. Again, sorry if this is in any way inappropriate.

Thanks, 
Rocco

**Comment by gruppjo** [comment]
Hi Rocco / @bagolol. In my opinion you reported this issue very nicely. You described which actions you performed that led to the error and you did some research trying to fix it on your own and provided the result of that as well. That's how it's done. Excellent :)
I'll look into it!

**Comment by gruppjo** [comment]
I just set up a project with tabs from scratch as you described, and ran `gulp protractor`
```
[10:09:49] Starting 'webdriver-update'...
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.19/chromedriver_mac32.zip...
[more gulp f
chromedriver_2.19.zip downloaded to /Users/jonathan/Projects/play/test/node_modules/protractor/selenium/chromedriver_2.19.zip
[10:09:51] Finished 'build-vars' after 1.22 s
[10:09:51] Finished 'eslint' after 1.85 s
[10:09:51] Starting 'linting'...
[10:09:51] Finished 'linting' after 4.36 μs
[10:09:51] Finished 'bower-fonts' after 1.87 s
[10:09:51] Finished 'styles' after 1.28 s
[10:09:51] Starting 'inject-all'...
[10:09:51] gulp-inject 5 files into index.html.
[10:09:51] gulp-inject 1 files into index.html.
[10:09:51] Finished 'inject-all' after 87 ms
[10:09:51] Starting 'serve'...
[10:09:51] Finished 'serve' after 9.62 ms
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000
    External: http://192.168.178.23:3000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.178.23:3001
 ---------------------------------------
[BS] Serving files from: app
[BS] Serving files from: .tmp
selenium-server-standalone-2.47.1.jar downloaded to /Users/jonathan/Projects/play/test/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar
[10:10:00] Finished 'webdriver-update' after 11 s
[10:10:00] Starting 'protractor'...
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.178.23:63362/wd/hub
.

Finished in 1.155 seconds
1 test, 6 assertions, 0 failures

Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
[10:10:05] Finished 'protractor' after 4.51 s
```

Honestly I'm not sure why it isn't working for you... I'm just gonna throw in some ideas and hope they are helpful:

1. When you navigate to `http://localhost:3000/#/main/debug` and scroll down to the password field, is it visible and does it grade your passwords when you type them in?
1. Just in case. Maybe set up again and see if that changes anything or delete the `node_modules` folder and install again using `npm install`
1. Did you leave `gulp watch` or any other task running while running `gulp protractor`? It needs to run alone.
1. the `protractor.conf.js` the generator provides assumes you have chrome installed. Is that the case? Or maybe there's something else different in your setup: baseUrl?
1. Maybe you can setup a small protractor example without the generator and see if that works.

**Comment by gruppjo** [comment]
It's a little weird that protractor obviously seems to run the tests but that they seem to fail. So it's not that likely that there's something wrong with the setup... Can you make sure the content of the following files are as they are in the demo?

https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/app/main/controllers/debug-ctrl.js
https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/app/main/templates/debug.html
https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/test/protractor/main-debug.spec.js

What happens, when you clone the demo and run `gulp protractor`?

**Comment by bagolol** [comment]
Hi, 

thanks for the swift reply. 

I just cloned the repo, run `npm install` and `bower install`. when I run `gulp protractor` I still get an error message: 

```
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.1.107:50165/wd/hub
FF

Failures:

  1) Debug page should grade passwords
   Message:
     ElementNotVisibleError: element not visible
  (Session info: chrome=46.0.2490.86)
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.11.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 33 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'Roccos-Air.default', ip: '192.168.1.107', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/_m/rxjymxms1zz6_mzr_jhwjj880000gn/T/.org.chromium.Chromium.Dl0nqc}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.86, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 35e73179a918cbb1a260eeafd85bc7a8
   Stacktrace:
     ElementNotVisibleError: element not visible
  (Session info: chrome=46.0.2490.86)
  (Driver info: chromedriver=2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708),platform=Mac OS X 10.11.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 33 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'Roccos-Air.default', ip: '192.168.1.107', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/_m/rxjymxms1zz6_mzr_jhwjj880000gn/T/.org.chromium.Chromium.Dl0nqc}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.86, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 35e73179a918cbb1a260eeafd85bc7a8
    at Array.forEach (native)
    at process._tickCallback (node.js:377:9)
Error
    at [object Object].<anonymous> (/Users/rocco/development/test/generator-m-ionic-demo/test/protractor/main-debug.spec.js:15:19)
From: Task: Asynchronous test function: it()
Error
    at [object Object].<anonymous> (/Users/rocco/development/test/generator-m-ionic-demo/test/protractor/main-debug.spec.js:9:3)
    at Object.<anonymous> (/Users/rocco/development/test/generator-m-ionic-demo/test/protractor/main-debug.spec.js:3:1)

  2) Debug page should grade passwords
   Message:
     Expected '' to equal 'weak'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/rocco/development/test/generator-m-ionic-demo/test/protractor/side-debug.spec.js:16:40)

  3) Debug page should grade passwords
   Message:
     Expected '' to equal 'medium'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/rocco/development/test/generator-m-ionic-demo/test/protractor/side-debug.spec.js:21:40)

  4) Debug page should grade passwords
   Message:
     Expected '' to equal 'strong'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/rocco/development/test/generator-m-ionic-demo/test/protractor/side-debug.spec.js:26:40)

Finished in 4.041 seconds
2 tests, 7 assertions, 4 failures

Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 4 test(s)
[launcher] overall: 4 failed spec(s)
[launcher] Process exited with error code 1

/Users/rocco/development/test/generator-m-ionic-demo/gulp/testing.js:42
      throw err;
      ^
Error: protractor exited with code 1
```
and to reply to your previous questions: 

1. yes, when I navigate to the relevant url the 'password strength check' works fine
3. no, I always make sure gulp watch isn't running
4. yes, I have chrome installed and it is up to date and I haven't changed the baseUrl
5. I tried to create my own tests, but protractor seems to be able to find only the elements with custom class names and not by binding or ionic class names

I also tried to resize the view setting it at 70, 80 or 90% so that all the elements were visible when the test is run, but that didn't change the error message.

Thanks, 
Rocco

**Comment by gruppjo** [comment]
Sorry you're having this issue. Honestly I'm not sure what else could cause this... 
What's the result of 
```
node -v
npm -v
```

**Comment by bagolol** [comment]
```
rocco:~ $ node -v
v5.0.0
rocco:~ $ npm -v
3.4.1
```

**Comment by gruppjo** [comment]
That's my current setup:
```
$ node -v
v5.0.0
$ npm -v
3.3.9
```
This should be fine I think... Just to be 100% sure, can you downgrade to npm 3.3.9 and try again?
Sorry. I have no further ideas. Please let me know if you find out something.

**Comment by gruppjo** [comment]
Closing due to inactivity and since we cannot reproduce. If anything more comes up, I'll reopen this issue.
