### ISSUE TITLE
Default Karma tests fail with "SyntaxError: missing ) after argument list"

### ISSUE THREAD

**Issue by SamuelMarks** [mwaylabs/generator-m-ionic#292]
Node.JS 5.1.1, yo 1.5.0, generator-m-ionic 1.4.1. Blank tests (were created with e.g.: `yo m-ionic:controller ErrorCtrl`, but `'should do something'` is the only test).

Full traceback (`gulp karma`):
```
"C:\Program Files (x86)\JetBrains\WebStorm 11.0.2\bin\runnerw.exe" J:\nodejs\node.exe C:\Users\Bar\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js --color --gulpfile J:\ionic_cryptonic\gulpfile.js karma
[14:22:26] Using gulpfile J:\ionic_cryptonic\gulpfile.js
[14:22:26] Starting 'eslint'...
[14:22:26] Starting 'jsonlint'...
[14:22:27] Finished 'jsonlint' after 500 ms
[14:22:27] Finished 'eslint' after 983 ms
[14:22:27] Starting 'linting'...
[14:22:27] Finished 'linting' after 10 µs
[14:22:27] Starting 'karma'...
14 12 2015 14:22:27.684:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
14 12 2015 14:22:27.689:INFO [launcher]: Starting browser PhantomJS
14 12 2015 14:22:27.692:ERROR [launcher]: { [SyntaxError: missing ) after argument list]
  source: 'function(obj) {\nobj || (obj = {});\nvar __t, __p = \'\', __j = Array.prototype.join;\nfunction print() { __p += __j.call(arguments, \'\') }\nwith (obj) {\n__p += \'(function (phantom) {\\n    var page = require(\\\'webpage\\\').create();\\n\\n    \';\n\n    if (exitOnResourceError) { ;\n__p += \'\\n        page.onResourceError = function () {\\n                phantom.exit(1)\\n            }\\n            < %\\n    }\\n    %>\\n\\n    \';\n\n    _.forOwn(pageOptions, function (value, key) { ;\n__p += \'\\n        page. < %= key % > =\\n        <\\n        %= value % >\\n            < %\\n    }) % >\\n\\n    < % _.forOwn(pageSettingsOptions, function (value, key) { %>\\n        page.settings. < %= key % > =\\n        <\\n        %= value % >\\n            < %\\n    }) % >\\n\\n    page.onConsoleMessage = function () {\\n            console.log.apply(console, arguments)\\n        }\\n\\n        < %\\n    if (debug) { %>\\n        function debugPage() {\\n            console.log(\\\'Launch the debugger page at http://localhost:9000/webkit/inspector/inspector.html?page=2\\\')\\n\\n            var debuggerWait = 15000\\n            console.log(\\\'Waiting \\\' + (debuggerWait / 1000) + \\\' seconds for debugger page to launch...\\\')\\n\\n            var launchPage = function () {\\n                console.log(\\\'Launching page \' +\n((__t = ( url )) == null ? \'\' : __t) +\n\'...\\\')\\n                page.open(\\\'\' +\n((__t = ( url )) == null ? \'\' : __t) +\n\'\\\')\\n            }\\n\\n            setTimeout(launchPage, 15000)\\n        }\\n\\n        debugPage()\\n        < %\\n    } else { %>\\n        page.open(\\\'\' +\n((__t = ( url )) == null ? \'\' : __t) +\n\'\\\')\\n        < %\\n    }\\n    %>\\n}(phantom))\\n\';\n\n}\nreturn __p\n}' }
SyntaxError: missing ) after argument list
    at Function (native)
    at J:\ionic_cryptonic\node_modules\lodash\index.js:10842:24
    at J:\ionic_cryptonic\node_modules\lodash\index.js:11115:29
    at J:\ionic_cryptonic\node_modules\lodash\index.js:8185:37
    at Function.template (J:\ionic_cryptonic\node_modules\lodash\index.js:10841:26)
    at Object._start (J:\ionic_cryptonic\node_modules\karma-phantomjs-launcher\index.js:58:26)
    at Object.<anonymous> (J:\ionic_cryptonic\node_modules\karma\lib\launchers\process.js:14:10)
    at emitOne (events.js:82:20)
    at Object.emit (events.js:169:7)
    at Object.start (J:\ionic_cryptonic\node_modules\karma\lib\launchers\base.js:41:10)
    at J:\ionic_cryptonic\node_modules\karma\lib\launcher.js:93:25
    at next (J:\ionic_cryptonic\node_modules\karma\node_modules\batch\index.js:118:7)
    at Batch.end (J:\ionic_cryptonic\node_modules\karma\node_modules\batch\index.js:154:5)
    at launch (J:\ionic_cryptonic\node_modules\karma\lib\launcher.js:110:15)
    at invoke (J:\ionic_cryptonic\node_modules\di\lib\injector.js:75:19)
    at Server.<anonymous> (J:\ionic_cryptonic\node_modules\karma\lib\server.js:170:32)
114 12 2015 14:23:27.691:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
```

**Comment by gruppjo** [comment]
Hi @SamuelMarks, this looks like a problem with lodash, not with the generator code. And currently we're not supporting Node 5.1.1 yet.

**Comment by SamuelMarks** [comment]
Hmm, actually looks like the issue can be resolved by upgrading karma. Still erring, but progress:
```
[00:28:39] Using gulpfile J:\ionic_cryptonic\gulpfile.js
[00:28:39] Starting 'eslint'...
[00:28:40] Starting 'jsonlint'...
[00:28:40] Finished 'jsonlint' after 449 ms
[00:28:40] Finished 'eslint' after 916 ms
[00:28:40] Starting 'linting'...
[00:28:40] Finished 'linting' after 9.5 µs
[00:28:40] Starting 'karma'...
15 12 2015 00:28:41.286:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
15 12 2015 00:28:41.292:INFO [launcher]: Starting browser PhantomJS
15 12 2015 00:28:42.148:INFO [PhantomJS 1.9.8 (Windows 8 0.0.0)]: Connected on socket qep-t2A-NLEHndmKAAAA with id 65172381
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 0 of 7 SUCCESS (0 secs / 0 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 1 of 7 SUCCESS (0 secs / 0.019 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0) module: main, service: Auth should do something FAILED
	Expected true to be false.
	    at e:/Projects/ionic_auth_scaffold/test/karma/main/auth-serv.spec.js:17
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 2 of 7 (1 FAILED) (0 secs / 0.025 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0) module: main, controller: ErrorCtrl should do something FAILED
	Error: [$injector:unpr] Unknown provider: $scopeProvider <- $scope <- ErrorCtrl
	http://errors.angularjs.org/1.4.8/$injector/unpr?p0=%24scopeProvider%20%3C-%20%24scope%20%3C-%20ErrorCtrl
	    at e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4337
	    at getService (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4485)
	    at e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4342
	    at getService (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4485)
	    at invoke (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4517)
	    at instantiate (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4534)
	    at e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:9197
	    at e:/Projects/ionic_auth_scaffold/app/bower_components/angular-mocks/angular-mocks.js:1883
	    at e:/Projects/ionic_auth_scaffold/test/karma/main/error-ctrl.spec.js:13
	    at invoke (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4526)
	    at workFn (e:/Projects/ionic_auth_scaffold/app/bower_components/angular-mocks/angular-mocks.js:2441)
	undefined
	Expected false to be true.
	    at e:/Projects/ionic_auth_scaffold/test/karma/main/error-ctrl.spec.js:17
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 3 of 7 (2 FAILED) (0 secs / 0.033 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 4 of 7 (2 FAILED) (0 secs / 0.037 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0) module: main, directive: errors should show text FAILED
	Expected '' to be 'this is the errors directive'.
	    at e:/Projects/ionic_auth_scaffold/test/karma/main/errors-dir.spec.js:20
	    at invoke (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4526)
	    at workFn (e:/Projects/ionic_auth_scaffold/app/bower_components/angular-mocks/angular-mocks.js:2441)
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 5 of 7 (3 FAILED) (0 secs / 0.046 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0) module: main, controller: UserCtrl should do something FAILED
	Error: [$injector:unpr] Unknown provider: $scopeProvider <- $scope <- UserCtrl
	http://errors.angularjs.org/1.4.8/$injector/unpr?p0=%24scopeProvider%20%3C-%20%24scope%20%3C-%20UserCtrl
	    at e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4337
	    at getService (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4485)
	    at e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4342
	    at getService (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4485)
	    at invoke (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4517)
	    at instantiate (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4534)
	    at e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:9197
	    at e:/Projects/ionic_auth_scaffold/app/bower_components/angular-mocks/angular-mocks.js:1883
	    at e:/Projects/ionic_auth_scaffold/test/karma/main/user-ctrl.spec.js:13
	    at invoke (e:/Projects/ionic_auth_scaffold/app/bower_components/angular/angular.js:4526)
	    at workFn (e:/Projects/ionic_auth_scaffold/app/bower_components/angular-mocks/angular-mocks.js:2441)
	undefined
	Expected false to be true.
	    at e:/Projects/ionic_auth_scaffold/test/karma/main/user-ctrl.spec.js:17
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 6 of 7 (4 FAILED) (0 secs / 0.051 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 7 of 7 (4 FAILED) (0 secs / 0.06 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 7 of 7 (4 FAILED) (0.007 secs / 0.06 secs)
[00:28:42] 'karma' errored after 1.59 s
[00:28:42] Error: 1
    at formatError (C:\Users\Bar\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\Bar\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (J:\ionic_cryptonic\node_modules\orchestrator\index.js:264:10)
    at J:\ionic_cryptonic\node_modules\orchestrator\index.js:275:28
    at finish (J:\ionic_cryptonic\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (J:\ionic_cryptonic\node_modules\orchestrator\lib\runTask.js:29:3)
    at removeAllListeners (J:\ionic_cryptonic\node_modules\karma\lib\server.js:332:7)
    at Server.<anonymous> (J:\ionic_cryptonic\node_modules\karma\lib\server.js:343:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at doNTCallback1 (node.js:441:9)
    at process._tickCallback (node.js:363:17)

Process finished with exit code 1
```

**Comment by gruppjo** [comment]
We'd appreciate any updates. Very much! Thanks for keeping us up to date so far.
