### ISSUE TITLE
karma tests fail on Node 5.3

### ISSUE THREAD

**Issue by SamuelMarks** [mwaylabs/generator-m-ionic#303]
Fresh `generator-m-ionic` and `yo` install with Node.JS 5.3 on Windows. Created a controller with `yo m-ionic:controller FooCtrl`.

### .yo-rc.json
```
{
  "generator-m-ionic": {
    "answers": {
      "appName": "example0",
      "appId": "com.company.example0",
      "ionicCss": false,
      "bowerPackages": [
        "angular-dynamic-locale#~0.1.27",
        "angular-translate#~2.8.1",
        "angular-translate-loader-static-files#~2.8.1",
        "localforage#~1.3.1"
      ],
      "platforms": [
        "ios",
        "android"
      ],
      "plugins": [
        "cordova-plugin-device",
        "cordova-plugin-statusbar"
      ],
      "appModule": "example0"
    }
  }
}
```

### `gulp karma`
```
[16:11:37] Using gulpfile ~\AppData\Local\Temp\a\gulpfile.js
[16:11:37] Starting 'eslint'...
[16:11:37] Starting 'jsonlint'...
[16:11:37] Finished 'jsonlint' after 452 ms
[16:11:37] Finished 'eslint' after 639 ms
[16:11:37] Starting 'linting'...
[16:11:37] Finished 'linting' after 10 μs
[16:11:37] Starting 'karma'...
27 12 2015 16:11:37.978:WARN [plugin]: Error during loading "C:\Users\Foo\App
Data\Local\Temp\a\node_modules/karma-phantomjs-launcher" plugin:
  Cannot find module 'phantomjs'
27 12 2015 16:11:38.011:WARN [watcher]: Pattern "C:/Users/Foo/AppData/Local/T
emp/a/test/karma/**/*.js" does not match any file.
27 12 2015 16:11:38.065:WARN [watcher]: Pattern "C:/Users/Foo/AppData/Local/T
emp/a/app/**/templates/*.html" does not match any file.
27 12 2015 16:11:38.094:INFO [karma]: Karma v0.13.16 server started at http://lo
calhost:9876/
27 12 2015 16:11:38.096:WARN [launcher]: Can not load "PhantomJS", it is not reg
istered!
  Perhaps you are missing some plugin?
```
This was resolved quickly by installing [`karma-phantomjs-launcher`](https://github.com/karma-runner/karma-phantomjs-launcher) and [`phantomjs`](https://www.npmjs.com/package/phantomjs) with:
```
npm install karma-phantomjs-launcher phantomjs --save-dev
```

And now I have this error (on [Linux](https://gist.github.com/SamuelMarks/a0965c56079610cbedca) also):
```
[16:16:43] Using gulpfile ~\AppData\Local\Temp\a\gulpfile.js
[16:16:43] Starting 'eslint'...
[16:16:44] Starting 'jsonlint'...
[16:16:44] Finished 'jsonlint' after 407 ms
[16:16:44] Finished 'eslint' after 647 ms
[16:16:44] Starting 'linting'...
[16:16:44] Finished 'linting' after 10 μs
[16:16:44] Starting 'karma'...
[12 2015 16:16:44.755:WARN [watcher]: [Pattern "C:/Users/Foo/AppData/Local/Temp/a/app/**/templates/*.html" does not match any file.
[32m27 12 2015 16:16:44.784:INFO [karma]: [Karma v0.13.16 server started at http://localhost:9876/
[32m27 12 2015 16:16:44.788:INFO [launcher]: [Starting browser PhantomJS
[32m27 12 2015 16:16:45.226:INFO [PhantomJS 1.9.8 (Windows 8 0.0.0)]: [Connected on socket _VPYK2rDIkJZKUdbAAAA with id 72528149
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
[1A[2KPhantomJS 1.9.8 (Windows 8 0.0.0) module: main, controller: FooCtrl should do something FAILED
	Error: [$injector:modulerr] Failed to instantiate module ngHtml2Js due to:
	Error: [$injector:nomod] Module 'ngHtml2Js' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
	http://errors.angularjs.org/1.4.8/$injector/nomod?p0=ngHtml2Js
	    at C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:2007
	    at ensure (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:1929)
	    at module (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:2257)
	    at C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:4435
	    at forEach (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:340)
	    at loadModules (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:4461)
	    at createInjector (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:4344)
	    at workFn (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular-mocks/angular-mocks.js:2428)
	http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=ngHtml2Js&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngHtml2Js'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fnomod%3Fp0%3DngHtml2Js%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2FC:/Users/Foo/AppData/Local/Temp/a%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3F7ff07aecce5af4039a1c32649be0ff2afcaebe47%3A2007%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3F7ff07aecce5af4039a1c32649be0ff2afcaebe47%3A1929)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3F7ff07aecce5af4039a1c32649be0ff2afcaebe47%3A2257)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3F7ff07aecce5af4039a1c32649be0ff2afcaebe47%3A4435%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3F7ff07aecce5af4039a1c32649be0ff2afcaebe47%3A340)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3F7ff07aecce5af4039a1c32649be0ff2afcaebe47%3A4461)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3F7ff07aecce5af4039a1c32649be0ff2afcaebe47%3A4344)%0A%20%20%20%20at%20workFn%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fbower_components%2Fangular-mocks%2Fangular-mocks.js%3F41fb2d656d9a871440ee139e6491d0e2b124ebc8%3A2428)%0A%20%20%20%20at%20attemptSync%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1789)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1777%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1762%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A627%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A357%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A2360%0A%20%20%20%20at%20attemptAsync%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1819)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1774%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1762%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A627%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A2354%0A%20%20%20%20at%20attemptAsync%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1819)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1774%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A1762%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A627%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A2215%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F578a1e5ff14db21b04e2d6db7fd0eda37042440c%3A678%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fadapter.js%3F3030709c83121e1b2ca4d1e657306b834fc13350%3A318%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fkarma.js%3A191%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fcontext.html%3A74
	    at forEach (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:340)
	    at loadModules (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:4461)
	    at createInjector (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:4344)
	    at workFn (C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular-mocks/angular-mocks.js:2428)
	    at C:/Users/Foo/AppData/Local/Temp/a/app/bower_components/angular/angular.js:4459
	Expected false to be true.
	    at C:/Users/Foo/AppData/Local/Temp/a/test/karma/main/foo-ctrl.spec.js:17
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 1 of 1 (1 FAILED) (0 secs / 0.012 secs)
[1A[2KPhantomJS 1.9.8 (Windows 8 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.005 secs / 0.012 secs)
[16:16:45] 'karma' errored after 782 ms
[16:16:45] Error: 1
    at formatError (C:\Users\Foo\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\Foo\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\Foo\AppData\Local\Temp\a\node_modules\orchestrator\index.js:264:8)
    at C:\Users\Foo\AppData\Local\Temp\a\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\Foo\AppData\Local\Temp\a\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\Users\Foo\AppData\Local\Temp\a\node_modules\orchestrator\lib\runTask.js:29:3)
    at removeAllListeners (C:\Users\Foo\AppData\Local\Temp\a\node_modules\karma\lib\server.js:332:7)
    at Server.<anonymous> (C:\Users\Foo\AppData\Local\Temp\a\node_modules\karma\lib\server.js:343:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1524:8)
    at nextTickCallbackWith1Arg (node.js:444:9)
    at process._tickCallback (node.js:366:17)
```

### Troubleshooting
So I installed [`karma-ng-html2js-preprocessor`](https://github.com/karma-runner/karma-ng-html2js-preprocessor) and [just as a punt!] [`gulp-ng-html2js`](https://www.npmjs.com/package/gulp-ng-html2js) with:
```
npm install karma-ng-html2js-preprocessor gulp-ng-html2js --save-dev
```

But that failed to resolve the latest errors. 

So I tried editing "karma.config.js" to explicitly reference the plugins, like so:
```
plugins: [
      'karma-ng-html2js-preprocessor', 'karma-phantomjs-launcher', 'karma-jasmine', 'karma-angular-filesort', 'karma-phantomjs-shim'
    ],
```

But that same error remained.

**Comment by gruppjo** [comment]
Hi @SamuelMarks.

The `karma-phantomjs-launcher` and `phantomjs` are installed by default as well as `karma-ng-html2js-preprocessor` and the karma setup should work out of the box. See https://github.com/mwaylabs/generator-m-ionic-demo/blob/1.5.0/package.json#L40-L46. We don't regularly test on windows and linux though

Maybe there were some issues during `npm install`? Removing `node_modules` and running `npm install` again might fix this.

Can you clone the demo https://github.com/mwaylabs/generator-m-ionic-demo run `npm i && bower install` and see if you run into the same errors?

**Comment by SamuelMarks** [comment]
Very recently clean installed Windows 10. Got same error after generating a new project with a controller. Running Node.JS 5.3.0 x64 with npm 3.3.12, yo 1.5.1, generator-m-ionic 1.5.0, bower 1.7.2, gulp 3.9.0.

`gulp karma` on [generator-m-ionic-demo](https://github.com/mwaylabs/generator-m-ionic-demo) works fine.

**Comment by SamuelMarks** [comment]
@gruppjo a cursory `diff` of the two and the issue doesn't jump straight out at me. Okay, I'll push it up into a repo for you, here's what's generated: https://github.com/SamuelMarks/generator-m-ionic-example from this [.yo-rc.json](https://github.com/SamuelMarks/generator-m-ionic-example/blob/master/.yo-rc.json).

**Comment by gruppjo** [comment]
The problem seem to be that you are using: `ngHtml2Js` module in your controller karma test, but you you removed all the html templates. Uncomment this line - https://github.com/SamuelMarks/generator-m-ionic-example/blob/master/test/karma/main/foo-ctrl.spec.js#L8
Or start using templates:
`yo m-ionic:template hi`
Either should fix the error you run into.
