### ISSUE TITLE
'gulp protractor' cant find chromedriver

### ISSUE THREAD

**Issue by Simpler1** [mwaylabs/generator-m-ionic#329]
I'm new to yo, but I just installed `yo m-ionic` (1.6.0 on Linux Mint) and most seems to be fine, but when I run `gulp protractor`, I get the following error:

```
$ gulp protractor
[21:28:55] Using gulpfile ~/github_projects/assets/gulpfile.js
[21:28:55] Starting 'clean'...
[21:28:55] Starting 'wiredep'...
[21:28:55] Starting 'environment'...
[21:28:55] Starting 'eslint'...
[21:28:55] Starting 'jsonlint'...
[21:28:55] Starting 'webdriver-update'...
selenium standalone is up to date.
chromedriver is up to date.
[21:28:55] gulp-inject 1 files into main/constants/config-const.js.
[21:28:55] Finished 'webdriver-update' after 363 ms
[21:28:55] Finished 'wiredep' after 555 ms
[21:28:55] Finished 'jsonlint' after 456 ms
[21:28:55] Finished 'environment' after 584 ms
[21:28:55] Starting 'build-vars'...
[21:28:55] gulp-inject 1 files into main/constants/config-const.js.
[21:28:55] Finished 'clean' after 675 ms
[21:28:55] Starting 'styles'...
[21:28:55] Starting 'bower-fonts'...
[21:28:55] Finished 'build-vars' after 245 ms
[21:28:56] Finished 'eslint' after 890 ms
[21:28:56] Starting 'linting'...
[21:28:56] Finished 'linting' after 4.69 μs
[21:28:56] Finished 'styles' after 233 ms
[21:28:56] Finished 'bower-fonts' after 108 ms
[21:28:56] Starting 'inject-all'...
[21:28:56] gulp-inject 5 files into index.html.
[21:28:56] gulp-inject 1 files into index.html.
[21:28:56] Finished 'inject-all' after 108 ms
[21:28:56] Starting 'serve'...
[21:28:56] Finished 'serve' after 7.67 ms
[21:28:56] Starting 'protractor'...
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3008
    External: http://192.168.1.20:3008
 -------------------------------------
          UI: http://localhost:3009
 UI External: http://192.168.1.20:3009
 -------------------------------------
[BS] Serving files from: app
[BS] Serving files from: .tmp
[launcher] Process exited with error code 1
/home/kevin/github_projects/assets/node_modules/protractor/node_modules/q/q.js:126
                    throw e;
                    ^

Error: Could not find chromedriver at /home/kevin/github_projects/assets/node_modules/protractor/selenium/chromedriver
    at LocalDriverProvider.addDefaultBinaryLocs_ (/home/kevin/github_projects/assets/node_modules/protractor/lib/driverProviders/local.js:54:15)
    at LocalDriverProvider.setupEnv (/home/kevin/github_projects/assets/node_modules/protractor/lib/driverProviders/local.js:71:8)
    at Runner.run (/home/kevin/github_projects/assets/node_modules/protractor/lib/runner.js:274:31)
    at TaskRunner.run (/home/kevin/github_projects/assets/node_modules/protractor/lib/taskRunner.js:123:19)
    at createNextTaskRunner (/home/kevin/github_projects/assets/node_modules/protractor/lib/launcher.js:216:20)
    at /home/kevin/github_projects/assets/node_modules/protractor/lib/launcher.js:239:7
    at _fulfilled (/home/kevin/github_projects/assets/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/kevin/github_projects/assets/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/kevin/github_projects/assets/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/kevin/github_projects/assets/node_modules/protractor/node_modules/q/q.js:573:44

/home/kevin/github_projects/assets/gulp/testing.js:42
      throw err;
      ^
Error: protractor exited with code 1
```

I have Chrome installed and it's up to date and working fine interactively.

I noticed that the following directory:
`/node_modules/protractor/selenium`

has the following two files:
```
chromedriver_2.20.zip
selenium-server-standalone-2.48.2.jar
```

If I try to manually extract chromedriver_2.20.zip, I get an error.

I've tried to reload protractor through npm, but the problem is the same.

Any ideas?  Thanks...

**Comment by Simpler1** [comment]
I ended up just deleting the `node_modules` directory and rerunning `npm install`.  It's now running fine. 

I think I had inadvertently canceled the download of chromedriver_2.20.zip because I thought it had completed and was hanging when attempting to run `gulp protractor` the first time.
