### ISSUE TITLE
Gulp protractor

### ISSUE THREAD

**Issue by PeaceDeveloper** [mwaylabs/generator-m-ionic#338]
The test 'Debug page should grade passwords' launch the message 'Failed:element not visible'.

**Comment by gruppjo** [comment]
Please provide more information.
1. How did you generate your project?
2. What other changes did you make after the generation of the project?
3. what OS are you on, node version, generator version
3. Please clone the demo repository https://github.com/mwaylabs/generator-m-ionic-demo and run `gulp protractor` 
4. report back

**Comment by PeaceDeveloper** [comment]
Ok!
1. I generate the project using  a normal workflow of generator-m-ionic. I selected sass, android as platform and sidemenu as ionic template.
2. I didn


node v4.3.1
npm  v.3.8.1
yo 1.7.0
generator-m-ionic 1.6.1
windows 10

**Comment by PeaceDeveloper** [comment]
Ok!
1. I generate the project using  a normal workflow of generator-m-ionic. I selected sass, android as platform and sidemenu as ionic template.
2. I didn't any change.
3. versions:
node v4.3.1
npm  v.3.8.1
yo 1.7.0
generator-m-ionic 1.6.1
windows 10
4. I cloned the project and ran gulp protractor. So, Log:

Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.144.2:59101/wd/hub
Started
FF

Failures:
1) Debug page should grade passwords
  Message:
    Failed: element not visible
      (Session info: chrome=49.0.2623.87)
      (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 73 milliseconds
    Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
    System info: host: 'PC-Tiago', ip: '192.168.144.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_66'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\tiago\AppData\Local\Temp\scoped_dir12324_7176}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 3135190e2e8b5f42e8be96b33e3f84ad
  Stack:
    ElementNotVisibleError: element not visible
      (Session info: chrome=49.0.2623.87)
      (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 73 milliseconds
    Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
    System info: host: 'PC-Tiago', ip: '192.168.144.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_66'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\tiago\AppData\Local\Temp\scoped_dir12324_7176}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 3135190e2e8b5f42e8be96b33e3f84ad
        at new bot.Error (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\atoms\error.js:108:18)
        at Object.bot.response.checkResponse (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\atoms\response.js:109:9)
        at C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:379:20
        at goog.async.run.processWorkQueue (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
        at process._tickCallback (node.js:364:9)
    Error
        at [object Object].ElementArrayFinder.applyAction_ (C:\Users\tiago\Desktop\teste\node_modules\protractor\lib\element.js:382:21)
        at [object Object].ElementArrayFinder.(anonymous function) [as sendKeys] (C:\Users\tiago\Desktop\teste\node_modules\protractor\lib\element.js:78:17)
        at [object Object].ElementFinder.(anonymous function) [as sendKeys] (C:\Users\tiago\Desktop\teste\node_modules\protractor\lib\element.js:711:7)
        at Object.<anonymous> (C:\Users\tiago\Desktop\teste\test\protractor\main\debug.spec.js:15:19)
        at C:\Users\tiago\Desktop\teste\node_modules\jasminewd2\index.js:96:23
        at new wrappedCtr (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\goog\base.js:2468:26)
        at controlFlowExecute (C:\Users\tiago\Desktop\teste\node_modules\jasminewd2\index.js:82:18)
    From: Task: Run it("should grade passwords") in control flow
        at Object.<anonymous> (C:\Users\tiago\Desktop\teste\node_modules\jasminewd2\index.js:81:14)
        at attemptAsync (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24)
        at QueueRunner.run (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9)
        at C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1801:16
        at C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1745:9
        at C:\Users\tiago\Desktop\teste\node_modules\jasminewd2\index.js:18:5
        at goog.async.run.processWorkQueue (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\Users\tiago\Desktop\teste\test\protractor\main\debug.spec.js:9:3)
        at addSpecsToSuite (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:743:25)
        at Env.describe (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:713:7)
        at jasmineInterface.describe (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:3219:18)
        at Object.<anonymous> (C:\Users\tiago\Desktop\teste\test\protractor\main\debug.spec.js:3:1)

2) Debug page should grade passwords
  Message:
    Failed: element not visible
      (Session info: chrome=49.0.2623.87)
      (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 34 milliseconds
    Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
    System info: host: 'PC-Tiago', ip: '192.168.144.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_66'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\tiago\AppData\Local\Temp\scoped_dir12324_7176}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 3135190e2e8b5f42e8be96b33e3f84ad
  Stack:
    ElementNotVisibleError: element not visible
      (Session info: chrome=49.0.2623.87)
      (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 34 milliseconds
    Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
    System info: host: 'PC-Tiago', ip: '192.168.144.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_66'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\tiago\AppData\Local\Temp\scoped_dir12324_7176}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 3135190e2e8b5f42e8be96b33e3f84ad
        at new bot.Error (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\atoms\error.js:108:18)
        at Object.bot.response.checkResponse (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\atoms\response.js:109:9)
        at C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:379:20
        at goog.async.run.processWorkQueue (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
        at process._tickCallback (node.js:364:9)
    Error
        at [object Object].ElementArrayFinder.applyAction_ (C:\Users\tiago\Desktop\teste\node_modules\protractor\lib\element.js:382:21)
        at [object Object].ElementArrayFinder.(anonymous function) [as sendKeys] (C:\Users\tiago\Desktop\teste\node_modules\protractor\lib\element.js:78:17)
        at [object Object].ElementFinder.(anonymous function) [as sendKeys] (C:\Users\tiago\Desktop\teste\node_modules\protractor\lib\element.js:711:7)
        at Object.<anonymous> (C:\Users\tiago\Desktop\teste\test\protractor\side\debug.spec.js:15:19)
        at C:\Users\tiago\Desktop\teste\node_modules\jasminewd2\index.js:96:23
        at new wrappedCtr (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\goog\base.js:2468:26)
        at controlFlowExecute (C:\Users\tiago\Desktop\teste\node_modules\jasminewd2\index.js:82:18)
    From: Task: Run it("should grade passwords") in control flow
        at Object.<anonymous> (C:\Users\tiago\Desktop\teste\node_modules\jasminewd2\index.js:81:14)
        at attemptAsync (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24)
        at QueueRunner.run (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9)
        at C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1801:16
        at C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1745:9
        at C:\Users\tiago\Desktop\teste\node_modules\jasminewd2\index.js:18:5
        at goog.async.run.processWorkQueue (C:\Users\tiago\Desktop\teste\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\Users\tiago\Desktop\teste\test\protractor\side\debug.spec.js:9:3)
        at addSpecsToSuite (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:743:25)
        at Env.describe (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:713:7)
        at jasmineInterface.describe (C:\Users\tiago\Desktop\teste\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:3219:18)
        at Object.<anonymous> (C:\Users\tiago\Desktop\teste\test\protractor\side\debug.spec.js:3:1)

2 specs, 2 failures
Finished in 5.883 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 2 test(s)
[launcher] overall: 2 failed spec(s)
[launcher] Process exited with error code 1

**Comment by gruppjo** [comment]
This problem persists if you run it a second time? I sometimes have glitches that the protractor tests fail on the first run.

**Comment by PeaceDeveloper** [comment]
The problem persists yet.
When the browser is starting by protractor, show me the error 'ERR_CONNECTION_REFUSED'. I don

**Comment by gruppjo** [comment]
Hmm... I'm out of ideas and I don't have a windows machine. Sorry.

Since this problem is not occurring on Mac I'd suggest to look around general problems with protractor/selenium webdriver on windows. Also you could try running the tests in a different browser and see if that changes anything. Do so using the `protractor.conf.js` https://github.com/angular/protractor/blob/master/docs/browser-setup.md. Maybe an older version of gulp-protractor doesn't have this issue?

That's all I can think of right now. Please report back with any findings so others can benefit from your research as well!

**Comment by PeaceDeveloper** [comment]
I think that isn't an isolated problem with protractor because I use it to do other tests in my machine. Maybe is other library that interfered on phantonjs.

Thank's!

**Comment by gruppjo** [comment]
Very odd... Good luck!

**Comment by DrakeWitt** [comment]
I'm also experiencing this issue however I'm on Mac OS

**Comment by gruppjo** [comment]
@DrakeWitt are you using version 1.9.2? I thought I had taken care of issues like this with this commit: https://github.com/mwaylabs/generator-m-ionic/issues/385

**Comment by DrakeWitt** [comment]
@gruppjo I am running the lastest m-generator-ionic from the npm repo. My OS is macOS Sierra and I'm running google chrome stable. I switched over to another mac that I own running El Capitan and it worked fine. Not sure if this is an issue with the beta or my environment.

**Comment by gruppjo** [comment]
Thanks for providing the specs of your setup. Let me know if you find out what's causing the error.

**Comment by gruppjo** [comment]
closing due to inactivity. Please comment if you have updates or need more help.
