### ISSUE TITLE
environment gulp task failing

### ISSUE THREAD

**Issue by silentFred** [mwaylabs/generator-m-ionic#371]
Playing around with the generator and the environment task is hitting a snag. Anyone else getting this error on with gulp-inject?

[19:56:04] 'environment' errored after 4.27 ms
[19:56:04] c:\Users\Frederick\Desktop\yo ionic\node_modules\gulp-inject\src\inject\index.js:127
      startTag,
              ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\Frederick\Desktop\yo ionic\node_modules\gulp-inject\index.js:4:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireFn (c:\Users\Frederick\Desktop\yo ionic\node_modules\gulp-load-plugins\index.js:47:14)
    at Object.defineProperty.get [as inject] (c:\Users\Frederick\Desktop\yo ionic\node_modules\gulp-load-plugins\index.js:85:18)
[19:56:05] Finished 'clean' after 25 ms
[19:56:05] Finished 'wiredep' after 65 ms

**Comment by silentFred** [comment]
npm install gulp-inject@3.0.0

**Comment by gruppjo** [comment]
thanks! possibly related #363
