### ISSUE TITLE
Cannot read config file: .eslintrc

### ISSUE THREAD

**Issue by stumpy1982** [mwaylabs/generator-m-ionic#382]
I generate a new project with the V1.8 on several machines with node version 6.2.2 and after installation i got this error:

```
Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^
Error: Cannot read config file: /Users/<username>/<projectfolder>/app/.eslintrc
Error: ENOENT: no such file or directory, open '/Users/<username>/<projectfolder>/app/.eslintrc'
Referenced from: /Users/<username>/<projectfolder>/<projectname>/test/karma/.eslintrc
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at readFile (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config/config-file.js:71:15)
    at loadLegacyConfigFile (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config/config-file.js:143:44)
    at loadConfigFile (/Users//<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config/config-file.js:223:22)
    at load (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config/config-file.js:500:18)
    at /Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config/config-file.js:531:22)
    at loadConfig (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/config.js:227:22)
    at processText (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/cli-engine.js:223:27)
    at CLIEngine.executeOnText (/Users/<username>/<projectfolder>/<projectname>/node_modules/eslint/lib/cli-engine.js:761:26)
```

The solution for this problem was to update the path of my protractor and karma .eslintrc to this: "../app/.eslintrc"

**Comment by nadouani** [comment]
+1

**Comment by lordgreg** [comment]
👍

**Comment by gruppjo** [comment]
I can no longer reproduce this as of today. @lordgreg, @nadouani, @stumpy1982. Can you confirm?

To make sure you're running the latest versions of `eslint` or `gulp-eslint` delete the node modules folder `rm -f node_modules` and run `npm install again`.
