### ISSUE TITLE
gulp/utils/Patcher.js missing

### ISSUE THREAD

**Issue by amuelli** [mwaylabs/generator-m-ionic#391]
when running the latest version of the generator `generators/app/templates/gulp/utils/Patcher.js ` is not copied to `gulp/utils/Patcher.js`.
This causes an error when running `gulp`

```
Error: Cannot find module './utils/Patcher'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alex/test/m-ionic/gulp/cordova.js:13:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by gruppjo** [comment]
Sorry for the slip-up. Try v.1.9.1 which I just published or get the file here: https://github.com/mwaylabs/generator-m-ionic/blob/master/generators/app/templates/gulp/utils/Patcher.js

**Comment by amuelli** [comment]
Thx, no problem. Just copied it manually.

**Comment by gruppjo** [comment]
I snuck in a small improvement to `gulp/cordova.js` in 1.9.1. Make sure to get that as well: https://github.com/mwaylabs/generator-m-ionic/commit/30d3eb4ea0c6246dc3820794801b4f2e03b4fee8#diff-81f2229a86fe59b84574227388a3ab99
