### ISSUE TITLE
Using `ionic upload` crashes

### ISSUE THREAD

**Issue by dkarchmer** [mwaylabs/generator-m-ionic#409]
It would be great for you guys to properly support `ionic upload`. 
Because you do not create an `ionic.config.json`, I manually created one (copying from another project) and then did

```
gulp build
ionic io init
ionic login
ionic upload
```

and got

```
Uploading app....
Saved app_id, writing to ionic.io.bundle.min.js...

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/david/ArchSys/iotile-mobile-ionic/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/david/ArchSys/iotile-mobile-ionic/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/david/ArchSys/iotile-mobile-ionic/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as info] (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Request._callback (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:150:11) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

ionic_cli should not crash (already reported: https://github.com/driftyco/ionic-cli/issues/1164), but clearly you are setting up something ionic_cli does not like.

Will add any comments from the ionic_cli team here, but it would be great if you guys supported and documented how to upload to http://view.ionic.io/

**Comment by gruppjo** [comment]
Hey @dkarchmer, for ionic platform integration you need to follow our [Ionic Platform Guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/ecosystems/ionic_platform.md). Have you done that?

Let me know how that works for you. `ionic upload` should work then.

**Comment by dkarchmer** [comment]
I did go through the Ionic Platform Guide (BTW, I suggest you start by documenting how to upload to view.ionic.io, and then you document how to use other platform features. The view.ionic.io is really different from the overall platform. For the view.ionic.io, you should not need to make any changes).

Commenting out the cordova.js should not be needed (as it is not needed when uploading a vanilla Ionic project), but I try with and without it.

The Ionic guys closed my issue as they just said it most be an ionic-m issue, and now you are closing my issue too. I have developed other Ionic apps, and have always used view.ionic.io to allow other team members to test them. But this is the first time I develop with ionic-m.

I will try to create a new project, without anything and try to upload that as a test, just in case this is something related to my plugins. The only plugin I added was the `cordova-plugin-ble-central`.

**Comment by dkarchmer** [comment]
This is what happens if I follow your instructions

```
npm install -g ionic
yo m-ionic  # Select all defaults
gulp serve  # OK
gulp build  # OK
ionic io init
ERR: Couldn't find ionic.config.json. Are you in an Ionic Project?
```

If I just create the file by hand

```
{
  "name": "ionicMTest",
  "app_id": ""
}
```

`ionic io init` will now work, but the upload will still fail. Maybe is related to the way you include the ionic JS files on the project.

Anyway, did you try it yourself? Does it work for you?

**Comment by gruppjo** [comment]
Sorry you didn't get it to work. 

Did you select `Ionic Platform integration` while running `yo m-ionic` or ran `yo m-ionic:ionic-platform` after project setup?
Did you run `bower install --save ionic-platform-web-client` to install the ionic-platform-web-client. Did you then run `ionic io init` and after that `gulp ionic-platform` to path the ionic-platform-library?

**Comment by gruppjo** [comment]
If you want you can link the issue you opened at ionic here as well so I can have a look!
