### ISSUE TITLE
gulp protractor - Error:  [...] .bin/webdriver-manager ENOENT

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#490]
The following error occurs due to a problem with `gulp-protractor` and yarn. Discussion started here: https://github.com/mwaylabs/generator-m-ionic/issues/469

**Fix**:
In your project folder (**be careful with rm**!), consider using `[trash](https://github.com/sindresorhus/trash)`.
```sh
# only remove gulp-protractor from node modules
rm -rf node_modules/gulp-protractor
# install using npm
npm install
```

**Error**:
```
$ gulp protractor
[13:22:23] Using gulpfile ~/Projects/play/test/gulpfile.js
[13:22:23] Starting 'clean'...
[13:22:23] Starting 'wiredep'...
[13:22:23] Starting 'environment'...
[13:22:23] Starting 'eslint'...
[13:22:24] Starting 'jsonlint'...
[13:22:24] Starting 'webdriver-update'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/jonathan/Projects/play/test/node_modules/.bin/webdriver-manager ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```
![image](https://cloud.githubusercontent.com/assets/1370779/23065173/6d88a734-f514-11e6-9fca-9b06c5356f25.png)

**Comment by gruppjo** [comment]
The following updates should take care of this issue:

Gregor
>package.json updates fuer yarn + protractor funktionalitaät:
>```
>"postinstall": "./node_modules/protractor/bin/webdriver-manager update"
>```
>neues devDependency:
>```
>"protractor": "^5.1.1",
>```
>Diese 2 Dings machen die yarn installation 100% supported

**Comment by gruppjo** [comment]
@lordgreg, I still get errors that I don't get with npm when installing and running `gulp protractor` with yarn:

<img width="722" alt="screen shot 2017-04-12 at 18 04 17" src="https://cloud.githubusercontent.com/assets/1370779/24967479/8aedb93e-1faa-11e7-9e2c-77d5d53b5398.png">

**Comment by lordgreg** [comment]
Hi @gruppjo,

I'm sorry for late response. You will have to wait few days more for me to get back to the personal office space :P

I will clone another demo of generator-m and do the same things I'm always doing. 

As soon as I find out what is causing the issue above, I'll post another response.

🎱
