### ISSUE TITLE
Cordova commands fail (run, build, preparte) when executed from generator gulp wrapper

### ISSUE THREAD

**Issue by squiso** [mwaylabs/generator-m-ionic#499]
Hi, Thanks for the amazing work on the ionic generator and build framework. I'm looking forward to incorporating this into my Ionic projects but having issues on Windows 10 at the moment. 

I've setup a new generator project following through the part 1 and 2 tutorial. Gulp watch and related tasks work as expected but any Cordova commands fail with the following error:
```
C:\Development\Local\adventure-island>gulp --cordova " run android"
[11:27:18] Using gulpfile C:\Development\Local\adventure-island\gulpfile.js
[11:27:18] Starting 'default'...
[11:27:18] Starting 'eslint-throw'...
[11:27:19] Starting 'jsonlint-throw'...
[11:27:19] Starting 'clean'...
[11:27:19] Starting 'wiredep'...
[11:27:19] Starting 'bower-fonts'...
[11:27:19] Starting 'environment'...
[11:27:19] Starting 'clean-res'...
[11:27:19] Finished 'default' after 453 ms
[11:27:19] gulp-inject 1 files into main\constants\config-const.js.
[11:27:20] Finished 'wiredep' after 958 ms
[11:27:20] Finished 'jsonlint-throw' after 1.02 s
[11:27:20] Finished 'clean-res' after 958 ms
[11:27:20] Starting 'resources'...
[11:27:20] Finished 'environment' after 1 s
[11:27:20] Starting 'build-vars'...
[11:27:20] gulp-inject Nothing to inject into main\constants\config-const.js.
[11:27:20] Finished 'build-vars' after 340 ms
[11:27:20] Finished 'bower-fonts' after 1.45 s
[11:27:20] Finished 'eslint-throw' after 1.97 s
[11:27:20] Starting 'linting-throw'...
[11:27:20] Finished 'linting-throw' after 28 μs
[11:27:20] Finished 'resources' after 566 ms
[11:27:20] Finished 'clean' after 1.62 s
[11:27:20] Starting 'styles'...
[11:27:21] Starting 'build-templates'...
[11:27:21] Starting 'build-assets'...
[11:27:23] Finished 'styles' after 2.86 s
[11:27:23] Starting 'inject-all'...
[11:27:23] gulp-imagemin: Minified 0 images
[11:27:23] gulp-inject 6 files into index.html.
[11:27:23] gulp-inject 1 files into index.html.
[11:27:23] Finished 'inject-all' after 238 ms
[11:27:23] Starting 'build-app'...
[11:27:23] Finished 'build-templates' after 2.64 s
[11:27:24] Finished 'build-assets' after 2.6 s
[11:27:24] Finished 'build-app' after 352 ms
[11:27:24] Starting 'build'...
[11:27:24] index.html 1.17 kB
[11:27:24] main\templates\debug.html 2.25 kB
[11:27:24] main\templates\list-detail.html 346 B
[11:27:24] main\templates\list.html 465 B
[11:27:24] main\templates\menu.html 1.18 kB
[11:27:24] main\assets\fonts\ionicons.eot 120.72 kB
[11:27:24] main\assets\fonts\ionicons.svg 333.83 kB
[11:27:24] main\assets\fonts\ionicons.ttf 188.51 kB
[11:27:24] main\assets\fonts\ionicons.woff 67.9 kB
[11:27:24] main\assets\images\yo@2x.png 2.2 kB
[11:27:24] all files 718.58 kB
[11:27:24] Finished 'build' after 61 ms
[11:27:24] Starting 'cordova-with-build'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\cordova\bin\cordova  run android ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**how did you set up your Generator-M-Ionic project, which options did you choose?**
Ionic Tabs
Android Platform
No plugins

**what changes did you introduce after setup?**
No changes

**what you are trying to do and what's going wrong?**
Cordova commands build, run, prepare all fail with the same error.

**what measures have you taken to fix it yourself and what was the result?**
1. Removed NPM, Bower folders and re-installed
2. Setup new generator project with same results
3. Added additional path to Windows environment variable
4. Ran command as administrator

**Which Operating System are you using and which version?**
Windows 10 Pro

Details about your node environment:
**node version**
v4.4.5

**npm version**
4.3.0

**generator version**
generator-m-ionic@1.11.0

**local Cordova CLI version**
[12:55:40] CLI version 3.9.1
[12:55:40] Local version 3.9.1

**Comment by lordgreg** [comment]
Hi @squiso and thanks for reporting the issue. Since I'm also someone who uses Windows OS, I don't have the same issue. Here is my question:
- is there a reason you are using Node version 4.4.5? Can you try to upgrade to current LTS version (at least?). With that, npm will also get upgraded.

What the error shows is that there's `NO ENTry`, meaning, he cannot find the `node_modules/cordova/bin/cordova`. 

Here are also few things you should do:
1. delete the whole `node_modules` folder,
2. do an `npm install` again.

There has to be a conflict in npm/node version and maybe cordova. 

Keep us informed! 👍

**Comment by squiso** [comment]
Hi @lordgreg thanks for the help. This had me pretty stumped and have to admit I didn't even think of checking my node version. I now realise why I need to keep node up to date. Lesson learnt 👍 

After updating to v6.10 and running a npm rebuild node-sass it fixed all the problems. Cordova and Livereload commands all working as expected.

**Comment by lordgreg** [comment]
Happy to see we've fixed the issue. 

Enjoy using Generator-M ;)

**Comment by squiso** [comment]
Thanks! Excited to introduce the new workflow to the team. I just wish I found it sooner!

**Comment by gruppjo** [comment]
Hi @squiso, thank you :)

For the initial issue: I also think the extra whitespace within the double-quotes might have caused the issue.

**Comment by gruppjo** [comment]
> I just wish I found it sooner!

Additionally, if you're on twitter and feel like it: You can suggest to the ionic folks to list this generator as a recommended way for building Ionic 1 apps. We've been trying to convince them to do so, but they have been reluctant so far ;)
