### ISSUE TITLE
gulp build --minify error

### ISSUE THREAD

**Issue by rafialikhan** [mwaylabs/generator-m-ionic#504]
Hi, the gulp build --minify is suddenly started throwing the following error. Was working fine till 7the of March. Any ideas? However it does build fine with just gulp build. 

[16:04:42] Starting 'build-language'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/ubuntu/repos/ApplicantPortalUI/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by MathiasTim** [comment]
mhhh just a guess, because we get this a lot in the last days: What Node Version are you using? There was also an `ENOENT` error with the cordova package in #500 #499 #503.
In this issue upgrading to Node 6.X fixed the problem.
